---
title: "US International Flight Data "
author: "Group 4"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=F}
# The package "ezids" (EZ Intro to Data Science) includes some helper functions we developed for the course. 
# Some of the frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
# You will need to install it (once) from GitHub.
# library(devtools)
# devtools::install_github("physicsland/ezids")
# Then load the package in your R session.
library(ezids)
```

```{r setup, include=FALSE}
# Some of common RMD options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
knitr::opts_chunk$set(warning = F, message = F)
# Can globally set option for number display format.
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
```

```{r read_csv, include = TRUE}
us_flight_data<-read.csv("International_Report_Departures_Project_1.csv")
str(us_flight_data)
```

```{r sort_columns, include = TRUE}
library(dplyr)
library(ggplot2)
top_carrier_df <- us_flight_data %>% group_by(carrier)%>%
  summarise(a_sum=length(carrier))
top_carrier_df <- top_carrier_df[order(-top_carrier_df$a_sum),]%>% top_n(5)

airports <- read.csv("Airport_Codes.csv")

us_flight_data <- merge(x = us_flight_data, y = airports, by.x="fg_apt", by.y="IATA")

carriers <- read.csv("carrier codes.csv")

us_flight_data <- merge(x = us_flight_data, y = carriers, by = "carrier")

top_carrier_df <- us_flight_data %>% group_by(Carrier_Name)%>%
  summarise(a_sum=length(Carrier_Name))
top_carrier_df <- top_carrier_df[order(-top_carrier_df$a_sum),]%>% top_n(5)

top_airport_df <- us_flight_data %>% group_by(Airport)%>%
  summarise(b_sum=length(Airport))
top_airport_df <- top_airport_df[order(-top_airport_df$b_sum),]%>% top_n(10)

top_country_df <- us_flight_data %>% group_by(Country)%>%
  summarise(c_sum=length(Country))
top_country_df <- top_country_df[order(-top_country_df$c_sum),]%>% top_n(5)
```


```{r sort_columns, include = TRUE}

ggplot()+geom_line(data=tt ,
             aes(x=Year,
                 color = Carrier_Name), stat="count")


ggplot(data=top_carrier_df, aes(x=reorder(Carrier_Name,-a_sum),y=a_sum)) +
geom_bar(stat="identity") 


ggplot(data=top_country_df, aes(x=reorder(Country,-c_sum),y=c_sum)) +
geom_bar(stat="identity") 


ggplot(data=airports_merged, aes(x=reorder(Airport,-b_sum),y=b_sum)) +
geom_bar(stat="identity") 
```

```{r sort_columns, include = TRUE}
us_flight_data <- us_flight_data[order(us_flight_data$Year,us_flight_data$Month),]
print(us_flight_data)
```

```{r departure_each_month, include = TRUE}
departures_each_month <- aggregate(data_dte ~ Year + Month, data = us_flight_data, FUN = length)
colnames(departures_each_month) <- c("Year","Month","Total_Flights")
print(departures_each_month)
```

```{r departures_by_season, include = TRUE}
season_data <- departures_each_month %>% 
      mutate(Season = case_when(departures_each_month$Month %in% c(12,1,2) ~ 'Winter',                                       departures_each_month$Month %in% c(3,4,5) ~ 'Spring',
                                departures_each_month$Month %in% c(6,7,8) ~ 'Summer',
                                departures_each_month$Month %in% c(9,10,11) ~ 'Fall'))

departure_each_season <- aggregate(Total_Flights ~ Year + Season, data = season_data, FUN = sum)
departure_each_season
```

```{r bar_plot, include = TRUE}
library(ggplot2)

ggplot(departure_each_season, aes(x = Season, y = Total_Flights, fill = Season)) +
  geom_bar(stat = "identity", width = 0.35) +
  labs(x = "Season", y = "Total Flights", title = "Total Flights per Season") +
  scale_fill_manual(values = c("Winter" = "blue", "Spring" = "green", "Summer" = "orange", "Fall" = "red")) +
  theme_minimal()
```
